MoviesDbVersion2/config/routes.rb
Rails.application.routes.draw do
  resources :showgenres
  resources :showactors
  resources :movieactors
  resources :moviegenres
  resources :genres
  resources :actors
  devise_for :users
  resources :shows
  resources :movies
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

MoviesDbVersion2/app/models/actor.rb
class Actor < ApplicationRecord
    belongs_to :movieactor
    belongs_to :showactor
end

MoviesDbVersion2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

MoviesDbVersion2/app/models/genre.rb
class Genre < ApplicationRecord
    belongs_to :moviegenre
    belongs_to :showgenre
end

MoviesDbVersion2/app/models/movie.rb
class Movie < ApplicationRecord
    #belongs_to :genre
    #has_many :genre
    belongs_to :moviegenre
    belongs_to :movieactor


    def self.mtsearch(mtsearch)
        if mtsearch
            Movie.where('movies.m_title like ?', "%#{mtsearch}%").uniq
        else
            Movie.all
        end
    end

    def self.mssearch(mssearch)
        if mssearch
            Movie.where('movies.m_studio like ?', "%#{mssearch}%").uniq
        else
            Movie.all
        end
    end

    def self.mdsearch(mdsearch)
        if mdsearch
            Movie.where('movies.m_director like ?', "%#{mdsearch}%").uniq
        else
            Movie.all
        end
    end

    def self.mgsearch(mgsearch)
        if mgsearch
        
            # Select m_title
            # From movies
            # Inner Join moviegenres On moviegenres.mg_movieid = movies.m_movieid
            # Inner Join genres On genres.g_genreid = moviegenres.mg_genreid
            # Where g_genrename = 'Comedy';

            #This replictes the raw sql query but in rails, "%#{mgsearch}%" is whatever the user inputs into the search bar
            Movie.joins("Inner Join moviegenres On moviegenres.mg_movieid = movies.m_movieid").joins("Inner Join genres On genres.g_genreid = moviegenres.mg_genreid").where('genres.g_genrename like ?', "%#{mgsearch}%").uniq
        # if masearch
            
        #     # Select m_title
        #     # From Movies, Actors, MovieActors
        #     # WHERE a_actorid = ma_actorid
        #     # AND m_movieid = ma_movieid
        #     # AND a_actorname = 'Tom Hanks';


        #     #This replictes the raw sql query but in rails, "%#{mgsearch}%" is whatever the user inputs into the search bar
        #     Movie.joins("Inner Join movieactors On movieactors.ma_movieid = movies.m_movieid").joins("Inner Join actors On actors.a_actorid = movieactors.ma_actorid").where('actors.a_actorname like ?', "%#{masearch}%").uniq
        else
            Movie.all
        end
    end

    def self.masearch(masearch)
        if masearch
            
            # Select m_title
            # From Movies, Actors, MovieActors
            # WHERE a_actorid = ma_actorid
            # AND m_movieid = ma_movieid
            # AND a_actorname = 'Tom Hanks';


            #This replictes the raw sql query but in rails, "%#{masearch}%" is whatever the user inputs into the search bar
            Movie.joins("Inner Join movieactors On movieactors.ma_movieid = movies.m_movieid").joins("Inner Join actors On actors.a_actorid = movieactors.ma_actorid").where('actors.a_actorname like ?', "%#{masearch}%").uniq
        else
            Movie.all
        end
    end


end

MoviesDbVersion2/app/models/movieactor.rb
class Movieactor < ApplicationRecord
    has_many :actor
    has_many :movie
end

MoviesDbVersion2/app/models/moviegenre.rb
class Moviegenre < ApplicationRecord
    has_many :genre
    has_many :movie
    #has_many :movies
end

MoviesDbVersion2/app/models/show.rb
class Show < ApplicationRecord
    belongs_to :showgenre
    belongs_to :showactor


    def self.stsearch(stsearch)
        if stsearch
            Show.where('shows.s_title like ?', "%#{stsearch}%").uniq
        else
            Show.all
        end
    end

    def self.sssearch(sssearch)
        if sssearch
            Show.where('shows.s_studio like ?', "%#{sssearch}%").uniq
        else
            Show.all
        end
    end

    def self.sdsearch(sdsearch)
        if sdsearch
            Show.where('shows.s_director like ?', "%#{sdsearch}%").uniq
        else
            Show.all
        end
    end

    def self.sgsearch(sgsearch)
        if sgsearch
            Show.joins("Inner Join showgenres On showgenres.sg_showid = shows.s_showid").joins("Inner Join genres On genres.g_genreid = showgenres.sg_genreid").where('genres.g_genrename like ?', "%#{sgsearch}%").uniq
       
        else
            Show.all
        end
    end

    def self.sasearch(sasearch)
        if sasearch
            Show.joins("Inner Join showactors On showactors.sa_showid = shows.s_showid").joins("Inner Join actors On actors.a_actorid = showactors.sa_actorid").where('actors.a_actorname like ?', "%#{sasearch}%").uniq
        else
            Show.all
        end
    end
end

MoviesDbVersion2/app/models/showactor.rb
class Showactor < ApplicationRecord
    has_many :actor
    has_many :show
end

MoviesDbVersion2/app/models/showgenre.rb
class Showgenre < ApplicationRecord
    has_many :genre
    has_many :show
end

MoviesDbVersion2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

MoviesDbVersion2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

MoviesDbVersion2/app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: %i[ show edit update destroy ]

  # GET /shows or /shows.json
  def index
    @shows = Show.all
    @shows = Show.stsearch(params[:stsearch]) if params[:stsearch].present?
    @shows = Show.sssearch(params[:sssearch]) if params[:sssearch].present?
    @shows = Show.sdsearch(params[:sdsearch]) if params[:sdsearch].present?
    @shows = Show.sgsearch(params[:sgsearch]) if params[:sgsearch].present?
    @shows = Show.sasearch(params[:sasearch]) if params[:sasearch].present?
  end

  # GET /shows/1 or /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows or /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to show_url(@show), notice: "Show was successfully created." }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1 or /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to show_url(@show), notice: "Show was successfully updated." }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1 or /shows/1.json
  def destroy
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url, notice: "Show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:s_title, :s_releaseDate, :s_studio, :s_director, :s_showid, :stsearch, :sssearch, :sdsearch, :sgsearch, :sasearch)
    end
end

MoviesDbVersion2/app/helpers/actors_helper.rb
module ActorsHelper
end

MoviesDbVersion2/app/helpers/application_helper.rb
module ApplicationHelper
end

MoviesDbVersion2/app/helpers/genres_helper.rb
module GenresHelper
end

MoviesDbVersion2/app/helpers/home_helper.rb
module HomeHelper
end

MoviesDbVersion2/app/helpers/movieactors_helper.rb
module MovieactorsHelper
end

MoviesDbVersion2/app/helpers/moviegenres_helper.rb
module MoviegenresHelper
end

MoviesDbVersion2/app/helpers/movies_helper.rb
module MoviesHelper
end

MoviesDbVersion2/app/helpers/showactors_helper.rb
module ShowactorsHelper
end

MoviesDbVersion2/app/helpers/showgenres_helper.rb
module ShowgenresHelper
end

MoviesDbVersion2/app/helpers/shows_helper.rb
module ShowsHelper
end

MoviesDbVersion2/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <%= link_to 'Movies App', root_path, class:"navbar-brand" %>
  <%# <a class="navbar-brand" href="#">Movies App</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Movies", movies_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Shows", shows_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Actors", actors_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Genres", genres_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
      

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

MoviesDbVersion2/app/views/home/index.html.erb
<h1>Movies App Home Page</h1>
<p>Find me in app/views/home/index.html.erb</p>