MoviesDbVersion2/config/routes.rb
Rails.application.routes.draw do
  resources :showgenres
  resources :showactors
  resources :movieactors
  resources :moviegenres
  resources :genres
  resources :actors
  devise_for :users
  resources :shows
  resources :movies
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

MoviesDbVersion2/app/models/actor.rb
class Actor < ApplicationRecord
    belongs_to :movieactor
    belongs_to :showactor
end

MoviesDbVersion2/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[ show edit update destroy ]

  # GET /actors or /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1 or /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors or /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to actor_url(@actor), notice: "Actor was successfully created." }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1 or /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to actor_url(@actor), notice: "Actor was successfully updated." }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1 or /actors/1.json
  def destroy
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url, notice: "Actor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_params
      params.require(:actor).permit(:a_actorname, :a_actorid)
    end
end

MoviesDbVersion2/app/helpers/actors_helper.rb
module ActorsHelper
end

MoviesDbVersion2/app/views/actors/_actor.html.erb
<div id="<%= dom_id actor %>">
  <p>
    <strong>A actorname:</strong>
    <%= actor.a_actorname %>
  </p>

  <p>
    <strong>A actorid:</strong>
    <%= actor.a_actorid %>
  </p>

</div>

MoviesDbVersion2/app/views/actors/_form.html.erb
<%= form_with(model: actor) do |form| %>
  <% if actor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :a_actorname, style: "display: block" %>
    <%= form.text_field :a_actorname %>
  </div>

  <div>
    <%= form.label :a_actorid, style: "display: block" %>
    <%= form.number_field :a_actorid %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

MoviesDbVersion2/app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render "form", actor: @actor %>

<br>

<div>
  <%= link_to "Show this actor", @actor %> |
  <%= link_to "Back to actors", actors_path %>
</div>

MoviesDbVersion2/app/views/actors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Actors</h1>

  <style>
    table,
    th,
    /* setting the text-align property to center*/
    th {
        /* padding: 5px; */
        text-align: center;
      }
  </style>

 <table class="table table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <% @actors.each do |actor| %>
        <%#= render actor %>
        
         <td><%= actor.a_actorname %></td>
        <td>
          <%= link_to "Actor Info", actor, class:"btn btn-danger" %>          
        </td>
      
      </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to "New actor", new_actor_path %>

MoviesDbVersion2/app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render "form", actor: @actor %>

<br>

<div>
  <%= link_to "Back to actors", actors_path %>
</div>

MoviesDbVersion2/app/views/actors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @actor %>

<div>
  <%= link_to "Edit this actor", edit_actor_path(@actor) %> |
  <%= link_to "Back to actors", actors_path %>

  <%= button_to "Destroy this actor", @actor, method: :delete %>
</div>