MoviesDbVersion2/config/routes.rb
Rails.application.routes.draw do
  resources :showgenres
  resources :showactors
  resources :movieactors
  resources :moviegenres
  resources :genres
  resources :actors
  devise_for :users
  resources :shows
  resources :movies
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

MoviesDbVersion2/app/models/movieactor.rb
class Movieactor < ApplicationRecord
    has_many :actor
    has_many :movie
end

MoviesDbVersion2/app/controllers/movieactors_controller.rb
class MovieactorsController < ApplicationController
  before_action :set_movieactor, only: %i[ show edit update destroy ]

  # GET /movieactors or /movieactors.json
  def index
    @movieactors = Movieactor.all
  end

  # GET /movieactors/1 or /movieactors/1.json
  def show
  end

  # GET /movieactors/new
  def new
    @movieactor = Movieactor.new
  end

  # GET /movieactors/1/edit
  def edit
  end

  # POST /movieactors or /movieactors.json
  def create
    @movieactor = Movieactor.new(movieactor_params)

    respond_to do |format|
      if @movieactor.save
        format.html { redirect_to movieactor_url(@movieactor), notice: "Movieactor was successfully created." }
        format.json { render :show, status: :created, location: @movieactor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movieactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movieactors/1 or /movieactors/1.json
  def update
    respond_to do |format|
      if @movieactor.update(movieactor_params)
        format.html { redirect_to movieactor_url(@movieactor), notice: "Movieactor was successfully updated." }
        format.json { render :show, status: :ok, location: @movieactor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movieactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movieactors/1 or /movieactors/1.json
  def destroy
    @movieactor.destroy

    respond_to do |format|
      format.html { redirect_to movieactors_url, notice: "Movieactor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movieactor
      @movieactor = Movieactor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movieactor_params
      params.require(:movieactor).permit(:ma_movieid, :ma_actorid)
    end
end

MoviesDbVersion2/app/helpers/movieactors_helper.rb
module MovieactorsHelper
end

MoviesDbVersion2/app/views/movieactors/_form.html.erb
<%= form_with(model: movieactor) do |form| %>
  <% if movieactor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movieactor.errors.count, "error") %> prohibited this movieactor from being saved:</h2>

      <ul>
        <% movieactor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ma_movieid, style: "display: block" %>
    <%= form.number_field :ma_movieid %>
  </div>

  <div>
    <%= form.label :ma_actorid, style: "display: block" %>
    <%= form.number_field :ma_actorid %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

MoviesDbVersion2/app/views/movieactors/_movieactor.html.erb
<div id="<%= dom_id movieactor %>">
  <p>
    <strong>Ma movieid:</strong>
    <%= movieactor.ma_movieid %>
  </p>

  <p>
    <strong>Ma actorid:</strong>
    <%= movieactor.ma_actorid %>
  </p>

</div>

MoviesDbVersion2/app/views/movieactors/edit.html.erb
<h1>Editing movieactor</h1>

<%= render "form", movieactor: @movieactor %>

<br>

<div>
  <%= link_to "Show this movieactor", @movieactor %> |
  <%= link_to "Back to movieactors", movieactors_path %>
</div>

MoviesDbVersion2/app/views/movieactors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movieactors</h1>

<div id="movieactors">
  <% @movieactors.each do |movieactor| %>
    <%= render movieactor %>
    <p>
      <%= link_to "Show this movieactor", movieactor %>
    </p>
  <% end %>
</div>

<%= link_to "New movieactor", new_movieactor_path %>

MoviesDbVersion2/app/views/movieactors/new.html.erb
<h1>New movieactor</h1>

<%= render "form", movieactor: @movieactor %>

<br>

<div>
  <%= link_to "Back to movieactors", movieactors_path %>
</div>

MoviesDbVersion2/app/views/movieactors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movieactor %>

<div>
  <%= link_to "Edit this movieactor", edit_movieactor_path(@movieactor) %> |
  <%= link_to "Back to movieactors", movieactors_path %>

  <%= button_to "Destroy this movieactor", @movieactor, method: :delete %>
</div>