MoviesDbVersion2/config/routes.rb
Rails.application.routes.draw do
  resources :showgenres
  resources :showactors
  resources :movieactors
  resources :moviegenres
  resources :genres
  resources :actors
  devise_for :users
  resources :shows
  resources :movies
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

MoviesDbVersion2/app/models/showactor.rb
class Showactor < ApplicationRecord
    has_many :actor
    has_many :show
end

MoviesDbVersion2/app/controllers/showactors_controller.rb
class ShowactorsController < ApplicationController
  before_action :set_showactor, only: %i[ show edit update destroy ]

  # GET /showactors or /showactors.json
  def index
    @showactors = Showactor.all
  end

  # GET /showactors/1 or /showactors/1.json
  def show
  end

  # GET /showactors/new
  def new
    @showactor = Showactor.new
  end

  # GET /showactors/1/edit
  def edit
  end

  # POST /showactors or /showactors.json
  def create
    @showactor = Showactor.new(showactor_params)

    respond_to do |format|
      if @showactor.save
        format.html { redirect_to showactor_url(@showactor), notice: "Showactor was successfully created." }
        format.json { render :show, status: :created, location: @showactor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @showactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showactors/1 or /showactors/1.json
  def update
    respond_to do |format|
      if @showactor.update(showactor_params)
        format.html { redirect_to showactor_url(@showactor), notice: "Showactor was successfully updated." }
        format.json { render :show, status: :ok, location: @showactor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @showactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showactors/1 or /showactors/1.json
  def destroy
    @showactor.destroy

    respond_to do |format|
      format.html { redirect_to showactors_url, notice: "Showactor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showactor
      @showactor = Showactor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def showactor_params
      params.require(:showactor).permit(:sa_showid, :sa_actorid)
    end
end

MoviesDbVersion2/app/helpers/showactors_helper.rb
module ShowactorsHelper
end

MoviesDbVersion2/app/views/showactors/_form.html.erb
<%= form_with(model: showactor) do |form| %>
  <% if showactor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(showactor.errors.count, "error") %> prohibited this showactor from being saved:</h2>

      <ul>
        <% showactor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sa_showid, style: "display: block" %>
    <%= form.number_field :sa_showid %>
  </div>

  <div>
    <%= form.label :sa_actorid, style: "display: block" %>
    <%= form.number_field :sa_actorid %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

MoviesDbVersion2/app/views/showactors/_showactor.html.erb
<div id="<%= dom_id showactor %>">
  <p>
    <strong>Sa showid:</strong>
    <%= showactor.sa_showid %>
  </p>

  <p>
    <strong>Sa actorid:</strong>
    <%= showactor.sa_actorid %>
  </p>

</div>

MoviesDbVersion2/app/views/showactors/edit.html.erb
<h1>Editing showactor</h1>

<%= render "form", showactor: @showactor %>

<br>

<div>
  <%= link_to "Show this showactor", @showactor %> |
  <%= link_to "Back to showactors", showactors_path %>
</div>

MoviesDbVersion2/app/views/showactors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Showactors</h1>

<div id="showactors">
  <% @showactors.each do |showactor| %>
    <%= render showactor %>
    <p>
      <%= link_to "Show this showactor", showactor %>
    </p>
  <% end %>
</div>

<%= link_to "New showactor", new_showactor_path %>

MoviesDbVersion2/app/views/showactors/new.html.erb
<h1>New showactor</h1>

<%= render "form", showactor: @showactor %>

<br>

<div>
  <%= link_to "Back to showactors", showactors_path %>
</div>

MoviesDbVersion2/app/views/showactors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @showactor %>

<div>
  <%= link_to "Edit this showactor", edit_showactor_path(@showactor) %> |
  <%= link_to "Back to showactors", showactors_path %>

  <%= button_to "Destroy this showactor", @showactor, method: :delete %>
</div>